import React, { Component } from 'react'
import moment from 'moment'
import { connect } from 'react-redux'
import mapStateToProps from './../Store/mapStateToProps'
import Block from './Web/Block'
import SectionHeader from './Web/SectionHeader'
import Grid from './Grid/Grid'
import Column from './Grid/Column'